<div id="hist">
	<div id="title">
		My Experiments
	</div>

	<div id="current">

	</div>

	<div id="current-tbl" style="display:none">

	<table id="curr" class="table table-hover">
    <thead>
      <tr>
        <th>Dificulty</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>

	</div>

	<div id="hist-lbl">
		History:
	</div>

	<table id="hist" class="table table-hover">
    <thead>
      <tr>
        <th>Dificulty</th>
        <th>Description</th>
        <th>Result</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

</div>