<div id="home">
	<div id="title">SleepEZ</div>

	<button type="button" 
	class="btn btn-primary btn-lg" id="btn-list">
		<span class="glyphicon glyphicon-flash" aria-hidden="true"></span> Start sleep experiment.
	</button>

	<button type="button" 
	class="btn btn-default btn-lg" id="btn-current-data">
		<span class="glyphicon glyphicon-equalizer" aria-hidden="true"></span> My sleep data
	</button>
</div>